// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package apiserver

import (
	"context"
	"github.com/google/wire"
	"github.com/mungdong/devkit/internal/apiserver/biz"
	"github.com/mungdong/devkit/internal/apiserver/handler"
	"github.com/mungdong/devkit/internal/apiserver/pkg/validation"
	"github.com/mungdong/devkit/internal/apiserver/store"
	"github.com/mungdong/devkit/internal/pkg/middleware/gin"
	"github.com/onexstack/onexstack/pkg/authz"
)

// Injectors from wire.go:

// NewServer initializes and creates the web server with all necessary dependencies using Wire.
func NewServer(contextContext context.Context, config *Config) (*Server, error) {
	dependencies := NewDependencies(contextContext)
	db, err := ProvideDB(config)
	if err != nil {
		return nil, err
	}
	storeStore := store.NewStore(db)
	v := authz.DefaultOptions()
	authzAuthz, err := authz.NewAuthz(db, v...)
	if err != nil {
		return nil, err
	}
	bizBiz := biz.NewBiz(storeStore, authzAuthz)
	validator := validation.New(storeStore)
	handlerHandler := handler.NewHandler(bizBiz, validator)
	userRetriever := &UserRetriever{
		store: storeStore,
	}
	serverConfig := &ServerConfig{
		Config:       config,
		Dependencies: dependencies,
		Handler:      handlerHandler,
		Retriever:    userRetriever,
		Authz:        authzAuthz,
	}
	server, err := NewWebServer(serverConfig)
	if err != nil {
		return nil, err
	}
	apiserverServer := &Server{
		cfg: serverConfig,
		srv: server,
	}
	return apiserverServer, nil
}

// wire.go:

// infrastructureSet groups all infrastructure-related providers.
// This keeps the main wire.Build call clean.
var infrastructureSet = wire.NewSet(
	ProvideDB, wire.NewSet(wire.Struct(new(UserRetriever), "*"), wire.Bind(new(gin.UserRetriever), new(*UserRetriever))), authz.ProviderSet,
)
